// data.js

const listings = [
    {
        id: 1,
        image: "https://via.placeholder.com/300", // Replace with actual image URLs
        title: "Cozy Beachfront House",
        type: "Entire home",
        guests: 4,
        bedrooms: 2,
        bathrooms: 1,
        price: 150,
        rating: (Math.random() * 5).toFixed(1), // Random rating between 0 and 5
    },
    {
        id: 2,
        image: "https://via.placeholder.com/300",
        title: "Luxury Mountain Cabin",
        type: "Entire home",
        guests: 6,
        bedrooms: 3,
        bathrooms: 2,
        price: 200,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 3,
        image: "https://via.placeholder.com/300",
        title: "Modern Apartment in City Center",
        type: "Private room",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        price: 100,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 4,
        image: "https://via.placeholder.com/300",
        title: "Spacious Family Home",
        type: "Entire home",
        guests: 8,
        bedrooms: 4,
        bathrooms: 3,
        price: 250,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 5,
        image: "https://via.placeholder.com/300",
        title: "Charming Studio Apartment",
        type: "Private room",
        guests: 2,
        bedrooms: 0,
        bathrooms: 1,
        price: 80,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 6,
        image: "https://via.placeholder.com/300",
        title: "Cozy Cottage in the Woods",
        type: "Entire home",
        guests: 4,
        bedrooms: 2,
        bathrooms: 1,
        price: 120,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 7,
        image: "https://via.placeholder.com/300",
        title: "Stylish Loft Apartment",
        type: "Private room",
        guests: 3,
        bedrooms: 1,
        bathrooms: 1,
        price: 110,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 8,
        image: "https://via.placeholder.com/300",
        title: "Historic Mansion",
        type: "Entire home",
        guests: 10,
        bedrooms: 5,
        bathrooms: 4,
        price: 500,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 9,
        image: "https://via.placeholder.com/300",
        title: "Cozy Urban Apartment",
        type: "Private room",
        guests: 2,
        bedrooms: 1,
        bathrooms: 1,
        price: 90,
        rating: (Math.random() * 5).toFixed(1),
    },
    {
        id: 10,
        image: "https://via.placeholder.com/300",
        title: "Seaside Villa",
        type: "Entire home",
        guests: 5,
        bedrooms: 3,
        bathrooms: 2,
        price: 300,
        rating: (Math.random() * 5).toFixed(1),
    },
];

export default listings;
